version: "3"
services:
  postgres:
    image: postgres:latest
    container_name: my-postgres-container
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    networks:
      - my-network
    volumes:
      - postgres-data:/var/lib/postgresql/data

networks:
  my-network:
    driver: bridge

volumes:
  postgres-data:
