version: "3"
services:
  postgres:
    image: postgres:latest
    container_name: my-postgres-container
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    networks:
      - my-network
    volumes:
      - postgres-data:/var/lib/postgresql/data

  # balsacar-be:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: balsacar-be-container
  #   environment:
  #     # Add any environment variables required by your Go application
  #     PORT: ${GO_APP_PORT}
  #   ports:
  #     - "${GO_APP_PORT}:${GO_APP_PORT}"
  #   networks:
  #     - my-network
  #   depends_on:
  #     - postgres

networks:
  my-network:
    driver: bridge

volumes:
  postgres-data:
